#
# addons_hb32_mingw_0703.yml
#
# input:  mingw_0703.zip
# input:  hb32_mingw_0703.zip
# input:  github sources
# output: addons_hb32_mingw_0703.zip
#

name: addons_hb32_mingw_0703

on:
#  push:
  schedule:
   - cron: "0 2 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'addons_hb32_mingw_0703'
        default: 'addons_hb32_mingw_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: load mingw_0703.zip from workflow
      uses: dawidd6/action-download-artifact@v3
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: load hb32_mingw_0703.zip from workflow
      uses: dawidd6/action-download-artifact@v3
      with:
         workflow: hb32_mingw_0703.yml
         workflow_conclusion: success
         name: hb32_mingw_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Unzip All
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         md c:\temp\harbour\comp
         7z x -y c:\temp\hb32_mingw_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\harbour\comp

    - name: Load Source Code
      env:
         REPO_SEFAZ:    https://github.com/JoseQuintas/sefazclass
         REPO_BOLETO:   https://github.com/JoseQuintas/boletoclass
         REPO_RMCHART:  https://github.com/JoseQuintas/rmchartclass
         REPO_WVGTEST:  https://github.com/JoseQuintas/wvgtest
         REPO_PDFCLASS: http://github.com/JoseQuintas/pdfclass
         REPO_HWGUI:    https://github.com/JoseQuintas/hwgui
         REPO_HMGE:     https://github.com/JoseQuintas/hmge
         REPO_HMG3:     https://github.com/JoseQuintas/hmg3
         REPO_OOHG:     https://github.com/JoseQuintas/oohg
         REPO_OOHGSAMP: https://github.com/JoseQuintas/oohg/samples
         REPO_DLGAUTO:  https://github.com/JoseQuintas/dlgauto
         PATH_SEFAZ:    c:\temp\harbour\addons\sefazclass
         PATH_BOLETO:   c:\temp\harbour\addons\boletoclass
         PATH_RMCHART:  c:\temp\harbour\addons\rmchartclass
         PATH_PDFCLASS: c:\temp\harbour\addons\pdfclass
         PATH_WVGTEST:  c:\temp\harbour\addons\wvgtest
         PATH_HWGUI:    c:\temp\harbour\addons\hwgui
         PATH_HMGE:     c:\temp\harbour\addons\hmge
         PATH_HMG3:     c:\temp\harbour\addons\hmg3
         PATH_OOHG:     c:\temp\harbour\addons\oohg
         PATH_ZEPACK:   c:\temp\harbour\addons\zepack
         PATH_DLGAUTO:  c:\temp\harbour\addons\dlgauto
      run: |
         c:
         git clone $env:REPO_SEFAZ       $env:PATH_SEFAZ        --depth 1
         git clone $env:REPO_BOLETO      $env:PATH_BOLETO       --depth 1
         git clone $env:REPO_RMCHART     $env:PATH_RMCHART      --depth 1
         git clone $env:REPO_WVGTEST     $env:PATH_WVGTEST      --depth 1
         git clone $env:REPO_PDFCLASS    $env:PATH_PDFCLASS     --depth 1
         git clone $env:REPO_HWGUI       $env:PATH_HWGUI        --depth 1
         git clone $env:REPO_HMGE        $env:PATH_HMGE         --depth 1
         git clone $env:REPO_HMG3        $env:PATH_HMG3         --depth 1
         git clone $env:REPO_OOHG        $env:PATH_OOHG         --depth 1
         git clone $env:REPO_OOHGSAMP    $env:PATH_OOHG\SAMPLES --depth 1
         git clone $env:REPO_DLGAUTO     $env:PATH_DLGAUTO      --depth 1

    - name: Build All
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         HBMK_CMD: -workdir=c:\temp -q -quiet
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw32\bin
      run: |
         c:

         cd c:\temp\harbour\addons\sefazclass
         hbmk2 sefazclass.hbp -q -rebuild

         cd c:\temp\harbour\addons\boletoclass
         hbmk2 boletoclass.hbp -q -rebuild

         cd c:\temp\harbour\addons\rmchartclass
         hbmk2 rmchartclass.hbp -q -rebuild

         cd c:\temp\harbour\addons\pdfclass
         hbmk2 pdfclass.hbp -q -rebuild

         cd c:\temp\harbour\addons\wvgtest
         hbmk2 wvgtest.hbp -q -rebuild

         cd c:\temp\harbour\addons\wvgtest\bostaurus
         hbmk2 bostaurus.hbp -q -rebuild

         cd c:\temp\harbour\addons\hwgui
         hbmk2 hbxml.hbp    -q -rebuild
         hbmk2 hwgui.hbp    -q -rebuild
         hbmk2 hwgdebug.hbp -q -rebuild
         hbmk2 procmisc.hbp -q -rebuild

         cd c:\temp\harbour\addons\hmge
         hbmk2 hmge.hbp -q -rebuild

         cd c:\temp\harbour\addons\hmg3
         hbmk2 hmg3.hbp -q -rebuild

         cd c:\temp\harbour\addons\oohg
         hbmk2 oohg.hbp -q -w0 -rebuild

         cd c:\temp\harbour\addons\dlgauto\source
         hbmk2 test hwgui.hbc -q -rebuild
         hbmk2 test hmg3.hbc  -q -rebuild
         hbmk2 test hmge.hbc  -q -rebuild
         hbmk2 test oohg.hbc  -q -rebuild
#         hbmk2 test gtwvg.hbc -q -rebuild

    - name: Create addons_hb32_mingw_0703.zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z a -r c:\temp\addons_hb32_mingw_0703.7z c:\temp\harbour\addons\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save addons_hb32_mingw_0703.zip to workflow
      uses: actions/upload-artifact@v4
      with:
         name: addons_hb32_mingw_0703
         path: c:\temp\addons_hb32_mingw_0703.7z

