#
# hb32_mingw_1420.yml
#
# input:  mingw_1420.zip
# input:  github sources
# output: hb32_mingw_1420.zip
#

name: hb32_mingw_1420

on:
#  push:
  schedule:
   - cron: "30 3 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hb32_mingw_1420'
        default: 'hb32_mingw_1420'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Source Code
      env:
         REPO: JoseQuintas/harbour32
      run: |
         c:
         git clone https://github.com/$env:repo c:\temp\harbour32 --depth 1

    - name: load mingw_1420.zip from workflow
      uses: dawidd6/action-download-artifact@v3
      with:
         workflow: mingw_1420.yml
         workflow_conclusion: success
         name: mingw_1420
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Unzip All
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         md c:\temp\comp
         7z x -y c:\temp\mingw_1420.7z -oc:\temp\comp

    - name: Build 32 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\comp\mingw32\bin;c:\temp\harbour\bin
      run: |
         c:
         cd c:\temp\harbour32
         mingw32-make clean install

    - name: Create hb32_mingw_1420.zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z a -r c:\temp\hb32_mingw_1420.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save hb32_mingw_1420.zip to workflow
      uses: actions/upload-artifact@v4
      with:
         name: hb32_mingw_1420
         path: c:\temp\hb32_mingw_1420.7z
