# General tests
#

name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'test'
        required: true

jobs:

  Build:

    runs-on: windows-latest ### windows-2019 ubuntu-18.04 macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Test Powershell
      env:
         Repo: ${{ github.repository }}
      shell: pwsh
      run: |
         d:
         echo $env:Repo
         dir

#
# Annotations
#

# on:
#    push:
#    schedule:
# minute hour day month dayweek
#       - cron: "5 1 2 * *"
#    workflow_dispatch:
#    inputs:
#      name:
#        description: 'Harbour 3.4 mingw 7.3'
#        default: 'hb34_0703'
#        required: true

#     - name: Download Internet
#       run: |
#        (New-Object System.Net.WebClient).DownloadFile('http://www.josequintas.com.br/arquivos/mingw_0703.zip', 'c:\temp\mingw_0703posix.7z')

#    - name: Download artifact
#      uses: dawidd6/action-download-artifact@v2
#      with:
#         workflow: bcc_0582.yml
#         workflow_conclusion: success
#         name: bcc_0582
#         path: c:\temp
#         repo: JoseQuintas/hbpack

#    - name: Save artifact
#      uses: actions/upload-artifact@v2
#      with:
#         name: bcc_0582
#         path: c:\temp\bcc_0582.7z

#    - name: Unzip
#      env:
#         PATH: c:\program files\7-zip
#      run: |
#         c:
#         md c:\temp\harbour
#         md c:\temp\harbour\comp
#         7z x -y c:\temp\mingw_0703.7z -oc:\temp\harbour\comp

#    - name: Clone repo
#      env:
#         REPO: ${{ github.repository }}
#      run: |
#         c:
#         git clone https://github.com/$env:repo c:\temp\harbour34 --depth 10
#         cd \temp\harbour34
#         git config user.email "you@example.com"
#         git config user.name "Your Name"
#         git pull https://github.com/vszakats/hb
#         git clone https://github.com/JoseQuintas/hbdeleted c:\harbour34\contrib\hbdeleted

#    - name: Run work
#      env:
#         HB_BUILD_CONTRIB: No
#         HB_BUILD_DYN: no
#         HB_BUILD_SHARED: no
#         HB_BUILD_STRIP: all
#         HB_COMPILER: mingw
#         HB_INSTALL_PREFIX: c:\temp\harbour
#         PATH: c:\temp\harbour\comp\mingw64\bin
#      run: |
#         c:
#         cd c:\temp\harbour34
#         mingw32-make clean install

#    - name: Zip
#      env:
#         PATH: c:\program files\7-zip
#      run: |
#         c:
#         cd \temp\harbour
#         7z a -r c:\temp\hb34_0703.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'



